---
- hosts: all
  become: yes
  tasks:

  - name: Add user to remote hosts
    user: name=ansible-admin2 groups=sudo shell=/bin/bash

  - name: Add SSH keys to remote hosts
    authorized_key: user=ansible-admin2 key="{{ lookup('file', "/etc/ansible/common/files/id_rsa.pub") }}"
