---
- hosts: all
  become: yes
  tasks:
    - name: Download deb
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb
        dest: /home/ansible-admin2/zabbix-release_6.4-1+ubuntu20.04_all.deb
        mode: '0666'

    - name: Install repository
      ansible.builtin.apt:
        deb: /home/ansible-admin2/zabbix-release_6.4-1+ubuntu20.04_all.deb

    - name: Remove .deb
      shell: 'rm /home/ansible-admin2/zabbix-release_6.4-1+ubuntu20.04_all.deb'

    - name: updating apt
      shell: 'apt update -y'

    - name: Install zabbix-agent
      apt:
        name: 'zabbix-agent'
        state: present
      notify:
        systemd zabbix-agent

    - name: Setting up the configuration
      shell: "sed -i 's|^Server=.*|Server=51.250.29.161|' /etc/zabbix/zabbix_agentd.conf && sed -i 's|^ServerActive=.*|ServerActive=51.250.29.161|' /etc/zabbix/zabbix_agentd.conf && sed -i 's|^Hostname=.*|Hostname=Zabbix-server|' /etc/zabbix/zabbix_agentd.conf" 

    - name: Restart zabbix agent
      become: true
      shell: 'systemctl restart zabbix-agent'

  handlers:
    - name: systemd zabbix-agent
      systemd:
        name: zabbix-agent.service
        enabled: yes
        state: started

